name: Build & Test

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist --snapshot --skip-publish -f build/ci/.goreleaser.yml

    - name: Run GoReleaser for root version
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist --snapshot --skip-publish -f build/ci/.goreleaser_root.yml

  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install restic
      run: |
        wget https://github.com/restic/restic/releases/download/v0.11.0/restic_0.11.0_linux_amd64.bz2
        bzip2 -d restic_0.11.0_linux_amd64.bz2
        sudo mv restic_0.11.0_linux_amd64 /usr/local/bin/restic
        sudo chown root:root /usr/local/bin/restic
        sudo chmod +x /usr/local/bin/restic

    - name: install redis-cli
      run: sudo apt-get install redis-tools

    - name: install xfsprogs
      run: sudo apt-get install xfsprogs

    - name: install xfsdump
      run: sudo apt-get install xfsdump

    - name: create xfs filesystem
      run: |
        dd if=/dev/zero of=loopfile.img bs=1M count=20
        mkfs.xfs loopfile.img
        sudo losetup /dev/loop10 loopfile.img
        mkdir xfsmount
        sudo mount /dev/loop10 xfsmount

    - name: Test xfs with sudo
      run: sudo go test -v ./test/pkg/source/xfstest/...
      env:
        RESTIC_PASSWORD: mongorepo

    - name: Test remaining sources
      run: go test -v $(go list ./test/... | grep -v github.com/mittwald/brudi/test/pkg/source/xfstest)
      env:
        RESTIC_PASSWORD: mongorepo
