name: Build & Test

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist --snapshot --skip-publish -f build/ci/.goreleaser.yml

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: lint
        uses: quay.io/mittwald/golangci-lint:0.0.8
        env:
          GOLANGCI_ADDITIONAL_YML: ${CI_PROJECT_DIR}/build/package/ci/.golangci.yml
        run: |
          golangci-lint run -v --fix ./...
          git diff --exit-code


  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install restic
      run: |
        wget https://github.com/restic/restic/releases/download/v0.11.0/restic_0.11.0_linux_amd64.bz2
        bzip2 -d restic_0.11.0_linux_amd64.bz2
        sudo mv restic_0.11.0_linux_amd64 /usr/local/bin/restic
        sudo chown root:root /usr/local/bin/restic
        sudo chmod +x /usr/local/bin/restic

    - name: install redis-cli
      run: sudo apt-get install redis-tools

    - name: Test
      run: go test -v ./...
      env:
        RESTIC_PASSWORD: mongorepo