name: Go

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Install restic
      run: sudo apt-get install restic

    - name: Update restic
      run: restic self-update

    - name: install redis-cli
      run: sudo apt-get install redis-tools

    - name: Test
      run: go test -v ./...
      env:
        RESTIC_PASSWORD: mongorepo