name: Master

on:
  push:
    branches:
      - master

jobs:

  publish:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v1.3
        with:
          args: --snapshot --skip-publish --rm-dist

      - name: Log into registry
        run: |
          docker login -u="${{ secrets.DOCKER_LOGIN_USER }}" -p="${{ secrets.DOCKER_LOGIN_PASSWORD }}"

      - name: Push latest image
        run: |
          docker push quay.io/mittwald/brudi:latest