name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and release image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker login -u "${{ secrets.DOCKER_LOGIN_USER }}" -p "${{ secrets.DOCKER_LOGIN_PASSWORD }}" quay.io

      - run: curl -sL https://git.io/goreleaser | bash -s -- --config build/ci/.goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_USER_TOKEN }}

      - run: curl -sL https://git.io/goreleaser | bash -s -- --config build/ci/.goreleaser_privileged.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_USER_TOKEN }}
