name: Tags

on:
  push:
    tags:
      - v*

jobs:

  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Unshallow
        run: git fetch --prune --unshallow

      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x

      -
        name: Log into registry
        run: |
          docker login -u="${{ secrets.DOCKER_LOGIN_USER }}" -p="${{ secrets.DOCKER_LOGIN_PASSWORD }}" quay.io

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}